import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import { GoogleAnalytics } from '@next/third-parties/google'

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">     
      <head>
<<<<<<< HEAD
      <GoogleAnalytics gaId={process.env.GG_ANALYTICS} />
=======
      <GoogleAnalytics gaId={process.env.GG_ANALYTICS!} />
>>>>>>> 2b13dd06218cbce560811acdd599803e3976b759
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
